### ISSUE TITLE
No algorithm worked! [Op:Conv2D]

### ISSUE THREAD

**Issue by WxlSky** [bubbliiiing/yolov4-tf2#16]
when I train yolov4 on my datasets:
Restoring weights from: /home/jm3090/wxl/Jm_code/tensorflow-yolov4-tflite-master/weights/yolov4.weights ... 
2020-12-27 17:21:05.708877: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.8
2020-12-27 17:21:08.769703: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.11
2020-12-27 17:21:08.775555: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2020-12-27 17:21:08.775785: W tensorflow/core/framework/op_kernel.cc:1763] OP_REQUIRES failed at conv_ops.cc:1094 : Not found: No algorithm worked!
Traceback (most recent call last):
  File "/home/jm3090/wxl/Jm_code/tensorflow-yolov4-tflite-master/train.py", line 165, in <module>
    app.run(main)
  File "/home/jm3090/.local/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/jm3090/.local/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/jm3090/wxl/Jm_code/tensorflow-yolov4-tflite-master/train.py", line 157, in main
    train_step(image_data, target)
  File "/home/jm3090/wxl/Jm_code/tensorflow-yolov4-tflite-master/train.py", line 86, in train_step
    pred_result = model(image_data, training=True)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 425, in call
    inputs, training=training, mask=mask)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py", line 560, in _run_internal_graph
    outputs = node.layer(*args, **kwargs)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1007, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py", line 248, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1020, in convolution_v2
    name=name)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1150, in convolution_internal
    name=name)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2604, in _conv2d_expanded_batch
    name=name)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 932, in conv2d
    _ops.raise_from_not_ok_status(e, name)
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 6862, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError: No algorithm worked! [Op:Conv2D]
Exception ignored in: <function Buckets.__del__ at 0x7fc081bb2488>
Traceback (most recent call last):
  File "/home/jm3090/anaconda3/lib/python3.7/site-packages/tensorflow/python/eager/monitoring.py", line 407, in __del__
AttributeError: 'NoneType' object has no attribute 'TFE_MonitoringDeleteBuckets'

**Comment by bubbliiiing** [comment]
环境配置兄弟，你的3090是不是要考虑cuda11
