### ISSUE TITLE
训练到20epo的时候报错了 

### ISSUE THREAD

**Issue by wypbin** [bubbliiiing/yolov4-tf2#30]
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x7fc45c92f0b8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop

**Comment by bubbliiiing** [comment]
啊？这个完全看不出来欸，重新开始一下吧

**Comment by wypbin** [comment]
有出现了。。。

Epoch 35/50
114/114 [==============================] - 110s 966ms/step - loss: 2.9490 - val_loss: 3.3958

Epoch 00035: ReduceLROnPlateau reducing learning rate to 0.0001250000059371814.
Epoch 36/50
 12/114 [==>...........................] - ETA: 1:31 - loss: 2.8962Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x00000228B4204710>>
Traceback (most recent call last):
  File "D:\anaconda\envs\tf2.2\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x00000228B4204550>>
Traceback (most recent call last):
  File "D:\anaconda\envs\tf2.2\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Variable.__del__ of <tkinter.IntVar object at 0x00000228B42049B0>>
Traceback (most recent call last):
  File "D:\anaconda\envs\tf2.2\lib\tkinter\__init__.py", line 332, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x00000228B4204A58>>
Traceback (most recent call last):
  File "D:\anaconda\envs\tf2.2\lib\tkinter\__init__.py", line 3507, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <bound method Variable.__del__ of <tkinter.IntVar object at 0x00000228B4204B70>>
Traceback (most recent call last):
  File "D:\anaconda\envs\tf2.2\lib\tkinter\__init__.py", line 332, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop

**Comment by yichanshiwoa** [comment]
我也遇到类似的问题，但是我的问题忘记了保存。

**Comment by yichanshiwoa** [comment]
Tcl_AsyncDelete: async handler deleted by the wrong thread最后报了一个这样的错误

**Comment by bubbliiiing** [comment]
加个这个试试

import matplotlib
#import matplotlib.pyplot as plt
matplotlib.use('Agg') #
from matplotlib import pyplot as plt
